#!/usr/bin/env python3
"""Flask web UI for the teaching agent.

This exposes a browser-based version of the terminal agent in agent.py.
It:

* Asks for the user's background and preferences via a form.
* Streams the transcript in (scaled) real time to the browser.
* Streams commentary events as they are generated by the OpenAI model.
* Lets the front-end highlight referenced transcript text and show
  commentary as expandable notification-style bubbles on the right.

Run (from this directory):

    export OPENAI_API_KEY=...  # or configure .env
    python flask_app.py

Then open http://127.0.0.1:5000/ in your browser.
"""

from __future__ import annotations

import json
import time
from typing import Iterable, List, Set

from flask import Flask, Response, jsonify, render_template, request, stream_with_context

import agent  # reuse transcript parsing and commentary logic


app = Flask(__name__)


@app.route("/")
def index() -> str:
    """Render the main UI: background form + transcript + commentary pane."""

    return render_template("index.html")


def _playback_events(
    transcript_path: str,
    user_profile: str,
    model: str,
    speed: float,
    commentary_style: str,
) -> Iterable[str]:
    """Internal generator yielding Server-Sent Events for playback.

    Events are JSON objects with a "type" field:

    - {"type": "segment", "timestamp": str, "text": str}
    - {"type": "commentary", "timestamp": str, "text": str,
       "highlight_phrases": [str, ...]}
    - {"type": "done"}
    """

    segments: List[agent.TranscriptSegment] = agent.load_transcript(transcript_path)
    client = agent.get_openai_client()

    if speed <= 0:
        speed = 1.0

    first_start = segments[0].start_seconds
    playback_start_wall = time.time() - (first_start / speed)

    window_segments: List[agent.TranscriptSegment] = []
    explained_phrases: Set[str] = set()

    # Initial event to confirm stream started
    yield "data: {\"type\": \"started\"}\n\n"

    for seg in segments:
        # Schedule based on timestamp and speed
        target_wall = playback_start_wall + (seg.start_seconds / speed)
        now = time.time()
        sleep_dur = target_wall - now
        if sleep_dur > 0:
            time.sleep(sleep_dur)

        # Send transcript segment to client
        segment_payload = {
            "type": "segment",
            "timestamp": seg.raw_timestamp,
            "text": seg.text,
        }
        yield f"data: {json.dumps(segment_payload)}\n\n"

        # Update sliding window for commentary context
        window_segments.append(seg)
        window_start_cutoff = seg.start_seconds - 90.0
        window_segments = [
            s for s in window_segments if s.start_seconds >= window_start_cutoff
        ]

        try:
            commentary = agent.generate_commentary(
                client=client,
                model=model,
                user_profile=user_profile,
                window_segments=window_segments,
                commentary_style=commentary_style,
                explained_phrases=explained_phrases,
            )
        except Exception as e:  # pragma: no cover - runtime API failures
            error_payload = {
                "type": "error",
                "timestamp": seg.raw_timestamp,
                "message": str(e),
            }
            yield f"data: {json.dumps(error_payload)}\n\n"
            continue

        if not commentary:
            continue

        # Extract highlighted phrases and filter pure repeats
        new_phrases = [
            p.strip()
            for p in agent.extract_highlight_phrases(commentary)
            if p.strip()
        ]

        if new_phrases and all(p in explained_phrases for p in new_phrases):
            continue

        explained_phrases.update(new_phrases)

        commentary_payload = {
            "type": "commentary",
            "timestamp": seg.raw_timestamp,
            "text": commentary,
            "highlight_phrases": new_phrases,
        }
        yield f"data: {json.dumps(commentary_payload)}\n\n"

    yield "data: {\"type\": \"done\"}\n\n"


@app.route("/stream")
def stream() -> Response:
    """Server-Sent Events endpoint streaming transcript + commentary.

    Query parameters:
    - transcript: path to transcript file (default: transcript.txt)
    - model: OpenAI model name (default: gpt-4o-mini)
    - speed: playback speed multiplier (float, default: 1.0)
    - commentary_style: low | medium | high (default: medium)
    - user_profile: URL-encoded profile string (from the form)
    """

    transcript_path = request.args.get("transcript", "transcript.txt")
    model = request.args.get("model", "gpt-4o-mini")
    commentary_style = request.args.get("commentary_style", "medium")
    user_profile = request.args.get("user_profile", "")

    try:
        speed = float(request.args.get("speed", "1.0"))
    except ValueError:
        speed = 1.0

    event_iter = _playback_events(
        transcript_path=transcript_path,
        user_profile=user_profile,
        model=model,
        speed=speed,
        commentary_style=commentary_style,
    )

    return Response(
        stream_with_context(event_iter),
        mimetype="text/event-stream",
        headers={"Cache-Control": "no-cache"},
    )


@app.post("/api/commentary")
def api_commentary() -> Response:
    """Generate commentary for a live, incrementally built transcript.

    The client sends a list of recent transcript segments plus the user's
    profile and commentary preferences. We reuse the same commentary logic
    from ``agent.generate_commentary`` that powers the recorded playback.

    Expected JSON payload:

        {
          "segments": [
            {"start_seconds": float, "raw_timestamp": str, "text": str},
            ...
          ],
          "user_profile": str,
          "commentary_style": "low" | "medium" | "high",
          "model": str
        }

    The response JSON has the shape:

        {
          "need_commentary": bool,
          "commentary": str,
          "highlight_phrases": [str, ...],
          "timestamp": str  # timestamp of the most recent segment
        }
    """

    try:
        data = request.get_json(force=True, silent=False)  # type: ignore[arg-type]
    except Exception:
        return jsonify({
            "need_commentary": False,
            "commentary": "",
            "highlight_phrases": [],
            "error": "Invalid JSON payload",
        }), 400

    segments_in = data.get("segments") if isinstance(data, dict) else None
    if not isinstance(segments_in, list) or not segments_in:
        # Nothing to analyze – gracefully indicate no commentary.
        return jsonify({
            "need_commentary": False,
            "commentary": "",
            "highlight_phrases": [],
        })

    user_profile = str(data.get("user_profile", ""))
    commentary_style = str(data.get("commentary_style", "medium"))
    model = str(data.get("model", "gpt-4o-mini"))

    # Map incoming dicts to agent.TranscriptSegment objects.
    segments: List[agent.TranscriptSegment] = []
    for item in segments_in:
        if not isinstance(item, dict):
            continue
        try:
            start_seconds = float(item.get("start_seconds", 0.0))
        except (TypeError, ValueError):
            start_seconds = 0.0
        raw_timestamp = str(item.get("raw_timestamp", "0:00"))
        text = str(item.get("text", "")).strip()
        if not text:
            continue
        segments.append(
            agent.TranscriptSegment(
                start_seconds=start_seconds,
                raw_timestamp=raw_timestamp,
                text=text,
            )
        )

    if not segments:
        return jsonify({
            "need_commentary": False,
            "commentary": "",
            "highlight_phrases": [],
        })

    # Build a sliding ~90s context window based on the most recent segment.
    last_seg = segments[-1]
    window_start_cutoff = last_seg.start_seconds - 90.0
    window_segments: List[agent.TranscriptSegment] = [
        s for s in segments if s.start_seconds >= window_start_cutoff
    ]

    try:
        client = agent.get_openai_client()
        commentary = agent.generate_commentary(
            client=client,
            model=model,
            user_profile=user_profile,
            window_segments=window_segments,
            commentary_style=commentary_style,
            explained_phrases=None,
        )
    except Exception as e:  # pragma: no cover - runtime API failures
        return jsonify({
            "need_commentary": False,
            "commentary": "",
            "highlight_phrases": [],
            "error": str(e),
        }), 500

    if not commentary:
        return jsonify({
            "need_commentary": False,
            "commentary": "",
            "highlight_phrases": [],
            "timestamp": last_seg.raw_timestamp,
        })

    highlight_phrases = [
        p.strip()
        for p in agent.extract_highlight_phrases(commentary)
        if p.strip()
    ]

    return jsonify({
        "need_commentary": True,
        "commentary": commentary,
        "highlight_phrases": highlight_phrases,
        "timestamp": last_seg.raw_timestamp,
    })


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    # Debug=True for local use; consider changing for production.
    app.run(debug=True)
